name: gopls
description: Official Go language server
languages:
  - go

source:
  go:
    package: golang.org/x/tools/gopls
    bin: gopls
    version: "v0.17.1"

lsp:
  command: gopls
  args: ["serve"]
  file_patterns:
    - "**/*.go"
    - "**/go.mod"
  extension_to_language:
    ".go": go

health:
  timeout_ms: 15000
